apiVersion: v1
kind:   PersistentVolumeClaim
metadata:
  name: imagens-pvc # este pvc tem o intuito de armazenar as imagens da aplicação
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi