apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias

spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom: #importando as configurações de configmap
        - configMapRef:
            name: sistema-configmap #nome do metadata do arquivo: sistema-noticias-config.yml
