apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80 #porta que o serviço está rodando dentro do cluster
      #targetPort: 80 #porta que o container portal-noticias está rodando
      nodePort: 30000 #porta que será acessada extarnamente
  selector:
    app: portal-noticias