apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 30001 #abrindo a porta para o mundo externo
  selector:
    app: sistema-noticias   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:
  HOST_DB: svc-db-noticias:3306 #conexão ao banco de dados que está no serviço svc-db-noticias
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa-teste
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deploy
spec:
  replicas: 2
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
  
  selector:
    matchLabels:
      app: sistema-noticias