apiVersion: v1
kind: Pod
metadata: 
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container # esse volume, como estou utilizando o minikube, terá que criar um volume com este nome dentor do minikube com o comando: minikube ssh, crie na raiz do minikube
          name: primeiro-pv 
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-2