apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: container-2
    image: redis:latest
    ports:
    - containerPort: 6379
  - name: container-3
    image: busybox:latest